import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {PubSubHubProvider} from "@/app/PubSubHubProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PubSub Demo Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <PubSubHubProvider>
      <body className={inter.className}>{children}</body>
    </PubSubHubProvider>
    </html>
  );
}
